services:
  postgres-video:
    image: postgres:16-alpine
    container_name: video-db
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - video_pg_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: video-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  localstack:
    image: localstack/localstack:3.5.0
    container_name: localstack
    environment:
      - SERVICES=sqs,sns
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init.sh:ro

volumes:
  video_pg_data:
  minio_data:
  localstack_data: