services:
  postgres-video:
    image: postgres:16-alpine
    container_name: video-db
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - video_pg_data:/var/lib/postgresql/data

volumes:
  video_pg_data: